version: "2"

run:
  go: "1.24"
  timeout: 10m
  tests: false
  allow-parallel-runners: true
  issues-exit-code: 2

linters:
  default: all
  disable:
    - bodyclose
    - containedctx     # Struct should not contain context, action does.
    - contextcheck
    - cyclop           # Complex functions are not good.
    - depguard
    - dogsled
    - dupl             # Check code duplications.
    - exhaustive       # Doesn't really make sense.
    - exhaustruct      # Doesn't really make sense.
    - forcetypeassert  # Priority: that can lead to serious crashes.
    - funlen           # Break long functions.
    - gochecknoglobals
    - gochecknoinits   # Init functions cause an import to have side effects,
    - err113
    - interfacebloat
    - ireturn          # Accept interface, return concrate.
    - lll
    - loggercheck         # Doesn't really make sense.
    - nestif           # Some nexted if statements are 8 or 9 deep.
    - nilnil           # A function should return either something valuable
    - nonamedreturns   # Either named return, or use simply `return`.
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage      # Blackbox testing is preffered.
    - unparam
    - varnamelen       # m, d, p < These are not so meaningful variables.
    - wastedassign
    - wrapcheck
    - wsl

  settings:
    funlen:
      lines: 110
      statements: 60
    cyclop:
      max-complexity: 60
    gocognit:
      min-complexity: 60
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: false
    varnamelen:
      ignore-names:
      - err
      - wg
      - id
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true

    lll:
      line-length: 120

  exclusions:
    paths:
      - v1beta1/types_jsonschema.go
      - v1beta1/marshal.go
      - v1beta1/marshal_test.go
