run:
  go: "1.22"
  timeout: 10m
  tests: false
  allow-parallel-runners: true
  issues-exit-code: 2

linters:
  enable-all: true
  disable:
    - bodyclose
    - containedctx     # Struct should not contain context, action does.
    - contextcheck
    - cyclop           # Complex functions are not good.
    - deadcode
    - depguard
    - dogsled
    - dupl             # Check code duplications.
    - execinquery
    - exhaustive       # Doesn't really make sense.
    - exhaustivestruct
    - exhaustruct      # Doesn't really make sense.
    - exportloopref
    - forcetypeassert  # Priority: that can lead to serious crashes.
    - funlen           # Break long functions.
    - gci
    - gochecknoglobals
    - gochecknoinits   # Init functions cause an import to have side effects,
    - goerr113
    - goimports        # acts weirdly, dci handles imports anyway
    - golint
    - gomnd            # Give constant values a name with constants.
    - ifshort
    - interfacebloat
    - interfacer
    - ireturn          # Accept interface, return concrate.
    - lll
    - loggercheck         # Doesn't really make sense.
    - maligned
    - nestif           # Some nexted if statements are 8 or 9 deep.
    - nilnil           # A function should return either something valuable
    - nonamedreturns   # Either named return, or use simply `return`.
    - nosnakecase
    - paralleltest
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - tagliatelle
    - testpackage      # Blackbox testing is preffered.
    - unparam
    - varcheck
    - varnamelen       # m, d, p < These are not so meaningful variables.
    - wastedassign
    - wrapcheck
    - wsl

linters-settings:
  gci:
    sections:
      - standard
      - blank
      - dot
      - default
      - prefix(github.com/open-component-model/ocm)
    custom-order: true
  funlen:
    lines: 110
    statements: 60
  cyclop:
    max-complexity: 46
    skip-tests: true
  gocognit:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 46
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: false
  varnamelen:
    ignore-names:
    - err
    - wg
    - id
  lll:
    line-length: 120
  gosec:
    exclude-generated: true

issues:
  exclude:
    - composites
  exclude-rules:
    - path: cmds/
      linters:
      - forbidigo
    - source: "https://"
      linters:
      - lll
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    - text: "shadow: declaration of \"ok\""
      linters:
        - govet
    - path: _test\.go
      linters:
      - gocyclo
      - errcheck
      - gosec
      - dupl
      - funlen
      - scopelint
    - text: "Spec.DeepCopyInto undefined"
      linters:
      - typecheck
    - text: "G601: Implicit memory aliasing in for loop"
      # Ignored cos why not, that was the request.
      linters:
      - gosec
    - source: "// .* #\\d+"
      linters:
      - godox
    - path: ignore/.*\.go
      linters:
      - dupword
