release:
  prerelease: auto # this should detect a release candidate and mark it as pre-release in GitHub

builds:
  - id: default
    binary: cty
    flags:
      - -tags
      - netgo release
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    goarm64:
      - v9.0

archives:
  - id: default
    builds:
      - default
    name_template: "cty_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    files:
      - none*

checksum:
  name_template: "cty_checksums.txt"

krews:
  - name: crd-to-yaml
    repository:
      owner: Skarlso
      name: crd-to-sample-yaml
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        # Whether to enable it or not.
        enabled: true

        # Whether to open the PR as a draft or not.
        draft: true
        # Base can also be another repository, in which case the owner and name
        # above will be used as HEAD, allowing cross-repository pull requests.
        base:
          owner: Skarlso
          name: crd-to-sample-yaml
          branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Update krew plugin {{ .ProjectName }} to {{ .Tag }}"
    homepage: https://crdtoyaml.com
    description: |
      Generate sample YAML files from Kubernetes CustomResourceDefinition (CRD) schemas.
      Supports multiple input sources including files, URLs, Git repositories, and Kubernetes clusters.
      Features include minimal mode, schema validation, comments, and HTML output generation.
    short_description: Generate sample YAML from CRD definitions