release:
  prerelease: auto # this should detect a release candidate and mark it as pre-release in GitHub

builds:
  - id: default
    binary: cty
    flags:
      - -tags
      - netgo release
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    goarm64:
      - v9.0

archives:
  - id: default
    builds:
      - default
    name_template: "cty_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    files:
      - none*

checksum:
  name_template: "cty_checksums.txt"
