[versions]
# IntelliJ Platform
intelliJPlatform = "2.18.1"

# Dependencies
junit = "4.13.2"
mockito = "5.23.0"
snakeyaml = "2.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }