apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.example.com
spec:
  group: example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                frontend:
                  description: |
                    Frontend properties
                    - image: string
                    - imagePullPolicy: string
                    
                    This is something amazing.
                  type: object
                  properties:
                    image:
                      type: string
                backend:
                  type: object
                  properties:
                    database:
                      type: string
            status:
              type: object
  scope: Namespaced
  names:
    plural: apps
    singular: app
    kind: App