apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresources.example.com
spec:
  group: example.com
  names:
    kind: TestResource
    listKind: TestResourceList
    plural: testresources
    singular: testresource
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TestResource for demonstrating schema validation
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: TestResourceSpec defines the desired state
            properties:
              name:
                description: Name of the resource
                type: string
              count:
                description: Count of items
                type: integer
                minimum: 1
                maximum: 100
              enabled:
                description: Whether the resource is enabled
                type: boolean
            required:
            - name
            type: object
          status:
            description: TestResourceStatus defines the observed state
            properties:
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: TestResource for demonstrating schema validation
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: TestResourceSpec defines the desired state (v1beta1)
            properties:
              name:
                description: Name of the resource
                type: string
              count:
                description: Count of items
                type: integer
                minimum: 5  # Breaking change: increased minimum
                maximum: 200  # Non-breaking: increased maximum
              enabled:
                description: Whether the resource is enabled
                type: boolean
              version:
                description: Version field (new required field)
                type: string
                pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"  # Breaking change: new pattern constraint
            required:
            - name
            - version  # Breaking change: new required field
            type: object
          status:
            description: TestResourceStatus defines the observed state
            properties:
              phase:
                type: string
              conditions:
                description: Conditions of the resource (new field)
                type: array
                items:
                  type: object
            type: object
        type: object
    served: true
    storage: true