apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata: {}
spec:
  additionalTags: {}
  bastion:
    allowedCIDRBlocks: [] # minItems 0 of type string
    ami: string
    disableIngressRules: true
    enabled: true
    instanceType: string
  controlPlaneEndpoint:
    host: string
    port: 1
  controlPlaneLoadBalancer:
    additionalSecurityGroups: [] # minItems 0 of type string
    crossZoneLoadBalancing: true
    healthCheckProtocol: string
    name: OyI7Q3Hn4r # ^[A-Za-z0-9]([A-Za-z0-9]{0,31}|[-A-Za-z0-9]{0,30}[A-Za-z0-9])$
    scheme: "internet-facing"
    subnets: [] # minItems 0 of type string
  identityRef:
    kind: "AWSClusterControllerIdentity"
    name: string
  imageLookupBaseOS: string
  imageLookupFormat: string
  imageLookupOrg: string
  network:
    cni:
      cniIngressRules:
      - description: string
        fromPort: 1
        protocol: string
        toPort: 1
    securityGroupOverrides: {}
    subnets:
    - availabilityZone: string
      cidrBlock: string
      id: string
      ipv6CidrBlock: string
      isIpv6: true
      isPublic: true
      natGatewayId: string
      routeTableId: string
      tags: {}
    vpc:
      availabilityZoneSelection: "Ordered"
      availabilityZoneUsageLimit: 3
      cidrBlock: string
      id: string
      internetGatewayId: string
      ipv6:
        cidrBlock: string
        egressOnlyInternetGatewayId: string
        poolId: string
      tags: {}
  region: string
  s3Bucket:
    controlPlaneIAMInstanceProfile: string
    name: pls.vm9y # ^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$
    nodesIAMInstanceProfiles: [] # minItems 0 of type string
  sshKeyName: string
status:
  bastion:
    addresses:
    - address: string
      type: string
    availabilityZone: string
    ebsOptimized: true
    enaSupport: true
    iamProfile: string
    id: string
    imageId: string
    instanceState: string
    networkInterfaces: [] # minItems 0 of type string
    nonRootVolumes:
    - deviceName: string
      encrypted: true
      encryptionKey: string
      iops: 1
      size: 8
      throughput: 1
      type: string
    privateIp: string
    publicIp: string
    rootVolume:
      deviceName: string
      encrypted: true
      encryptionKey: string
      iops: 1
      size: 8
      throughput: 1
      type: string
    securityGroupIds: [] # minItems 0 of type string
    spotMarketOptions:
      maxPrice: string
    sshKeyName: string
    subnetId: string
    tags: {}
    tenancy: string
    type: string
    userData: string
    volumeIDs: [] # minItems 0 of type string
  conditions:
  - lastTransitionTime: 2024-10-11T12:48:44Z
    message: string
    reason: string
    severity: string
    status: string
    type: string
  failureDomains: {}
  networkStatus:
    apiServerElb:
      attributes:
        crossZoneLoadBalancing: true
        idleTimeout: 1
      availabilityZones: [] # minItems 0 of type string
      dnsName: string
      healthChecks:
        healthyThreshold: 1
        interval: 1
        target: string
        timeout: 1
        unhealthyThreshold: 1
      listeners:
      - instancePort: 1
        instanceProtocol: string
        port: 1
        protocol: string
      name: string
      scheme: string
      securityGroupIds: [] # minItems 0 of type string
      subnetIds: [] # minItems 0 of type string
      tags: {}
    securityGroups: {}
  ready: false
