name: Check for diff after manifest and generated targets

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  diff-check-manifests:
    name: Check for diff
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: '${{ github.workspace }}/go.mod'
    - name: Restore Go cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: /home/runner/work/_temp/_github_home/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: go mod tidy
      run: |
        go mod tidy
    - name: Check for diff
      run: |
        git diff --exit-code --shortstat
